// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 3);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.migration.version", 122);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[]},\"seen\":[\"save-to-pocket-button\"],\"dirtyAreaCache\":[],\"currentVersion\":17,\"newElementCount\":0}");
user_pref("distribution.iniFile.exists.appversion", "98.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220313140707");
user_pref("extensions.lastAppVersion", "98.0.1");
user_pref("extensions.lastPlatformVersion", "98.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"a3f69a2a-c2c2-402b-9418-0bfd07e7842b\",\"formautofill@mozilla.org\":\"f3077798-39d7-411a-bfd4-99866e6eda32\",\"pictureinpicture@mozilla.org\":\"d23de00d-3d33-46d8-a51c-430be9293d27\",\"screenshots@mozilla.org\":\"ea7f8e1e-a740-40d6-aaad-b97578f122d9\",\"webcompat-reporter@mozilla.org\":\"996ffc59-6d63-4d8b-b263-cbab4094cfca\",\"webcompat@mozilla.org\":\"ca148606-1780-4c37-a035-dab946e3cbd9\",\"default-theme@mozilla.org\":\"a334aa5f-14cb-4a15-b90e-b07c9df49d38\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("security.sandbox.content.tempDirSuffix", "90e428bb-3b8d-4a5a-804c-9349677add59");
user_pref("toolkit.startup.last_success", 1647287154);
user_pref("toolkit.telemetry.cachedClientID", "7f2d3693-3565-41b5-ae09-358319cfa631");
user_pref("toolkit.telemetry.previousBuildID", "20220313140707");
